name: "My first workflow"
run-name: "My First Run"

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
    paths:
      - 'force-app/**'
  pull_request:
    branches:
      - master
      - main
      - uat
    paths:
      - 'force-app/**'
    types:
      - opened
      - synchronize
      - closed

env:
  ENGINES: "eslint,eslint-lwc,eslint-typescript,pmd,pmd-appexchange,retire-js,sfge,cpd"
  CATEGORY: "Design,Best Practices,Code Style,Performance,Security"
  OUTPUT_FILE: "reports/scan-reports.html"
  SF_ALIAS_VAR: "prod"
  TEST_LEVEL: "RunLocalTests"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Salesforce CLI
        run: |
          # Use Node.js to install Salesforce CLI
          npm install -g @salesforce/cli

      - name: verify sfdx installation
        run: |
          # Verify the installation
          sf --version

      - name: Install Salesforce Code Analyzer
        run: |
          # Install the Salesforce Code Analyzer
          sf plugins install @salesforce/sfdx-scanner

      - name: Run Salesforce Code Analyzer
        run: |
          # Run the Salesforce Code Analyzer
          mkdir reports
          sf scanner run --format html --target "delta/force-app/main/default" --engine ${{ env.ENGINES }} --category ${{ env.CATEGORY }} --outfile ${{ env.OUTPUT_FILE }}

      - name: Upload a Build Artifact
        if: always() # success() || failure()
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: scan-reports
          path: reports/scan-reports.html
          if-no-files-found: ignore

      - name: Decrypt JWT key
        run: |
          # Decrypt the JWT key file
          openssl enc -nosalt -aes-256-cbc -d -in ${{ secrets.JWT_ENCRYPTION_KEY_FILE }} -out ${{ secrets.JWT_KEY_FILE }} -base64 -K ${{ secrets.ENCRYPTION_KEY }} -iv ${{ secrets.ENCRYPTION_IV }}

      - name: Authenticate to Salesforce
        run: |
          # Authenticate to Salesforce using JWT
          sf org login jwt --username ${{ vars.SF_USER_NAME }} --jwt-key-file ${{ secrets.JWT_KEY_FILE }} --client-id ${{ secrets.CONSUMER_KEY }} --set-default --alias ${{ vars.SF_ALIAS }} --instance-url ${{ vars.SF_INSTANCE_URL }}

      - name: Run the LocalTest Cases 
        run: |
          # Run the LocalTest Cases
          # https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_apex_commands_unified.htm
          sf apex run test --target-org ${{ vars.SF_ALIAS }} --test-level ${{ env.TEST_LEVEL }} --code-coverage --result-format human --output-dir ./ --wait 10

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Validate to Salesforce
        run: |
          # Validate to Salesforce
          sf project deploy start --target-org ${{ vars.SF_ALIAS }} --source-dir ./force-app --dry-run --wait 10
          sf project deploy start --target-org ${{ vars.SF_ALIAS }} --manifest ./package.xml --dry-run --wait 10
