name: "My First Workflow"
run-name: "My First Run"

## Push event should only work in case of feature branches
on: 
  # workflow_dispatch:
  push:
    branches:
      - feature/**
    paths:
      - 'force-app/**'
  # pull_request:


jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout"
        uses: actions/checkout@v2 
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: |
          # Use Node.js to install Salesforce CLI
          npm install -g @salesforce/cli
          sf --version
      - name: Decrypt JWT Key
        run: |
          # Decrypt the JWT key
          openssl enc -nosalt -aes-256-cbc -d -in ${{ secrets.JWT_ENCRYPTION_KEY_FILE }} -out ${{ secrets.JWT_KEY_FILE }} -base64 -K ${{ secrets.ENCRYPTION_KEY }} -iv ${{ secrets.ENCRYPTION_IV }}
      - name: Authenticate to Salesforce
        run: |
          # Authenticate to Salesforce
          sf org login jwt --username ${{ secrets.SF_USER_NAME }} --jwt-key-file ${{ secrets.JWT_KEY_FILE }} --client-id ${{ secrets.CONSUMER_KEY }} --set-default --alias ${{ vars.SF_ALIAS }} --instance-url ${{ vars.SF_INSTANCE_URL }}

      - name: Validate to Salesforce
        run: |
          # Validate to Salesforce
          sf project deploy start --target-org ${{ vars.SF_ALIAS }} --source-dir force-app --dry-run --wait 10
          sf project deploy start --target-org ${{ vars.SF_ALIAS }} --manifest manifest/package.xml --dry-run --wait 10