name: "My first workflow"
run-name: "My First Run"

on: [push]

jobs: # A Workflow run is made up of one or more jobs
  build: #Job Name
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: |
          # Use Node.js to install Salesforce CLI
          npm install -g @salesforce/cli
      - name: verify sfdx installation
        run: |
          # Verify the installation
          sf --version
      - name: Decrypt JWT key
        run: |
          # Decrypt the JWT key file
          openssl enc -nosalt -aes-256-cbc -d -in ${{ secrets.JWT_ENCYRPTION_KEY_FILE }} -out ${{ secrets.JWT_KEY_FILE }} -base64 -K ${{ secrets.ENCYRPTION_KEY }} -iv ${{ secrets.ENCYRPTION_IV }}
      - name: Authenticate to Salesforce
        run: |
          # Authenticate to Salesforce using JWT
          sf org login jwt --username ${{ vars.SF_USER_NAME }} --jwt-key-file ${{ secrets.JWT_KEY_FILE }} --client-id ${{ secrets.CONSUMER_KEY }} --set-default --alias ${{ vars.SF_ALIAS }} --instance-url ${{ vars.SF_INSTANCE_URL }}

